### ISSUE TITLE
Radio button / checkbox: a11y UX and docs

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/OrionStatelessComponents__ods-inputoptions#13]
## What is the requested web component?

Radio buttons and checkboxes are a cornerstone interaction element for forms and various other user interactions. 

## Features

> Please list out the features of the proposed web component

- [x] Addresses all a11y interactions 
- [x] Design documentation is completed and uploaded to company resource 

## Is there any prior art related to this proposal?

- [x] YES
- [ ] NO

### Prior art

https://github.com/AlaskaAirlines/OrionStatelessComponents__ods-inputoptions

There is also a PR for a refactor as to how the component works. 

There is NO official Auro design spec. The above work is Orion based. 

## Agreement

By checking the box below I acknowledge that the proposed web component does not duplicate any existing feature or functionality within the Auro Design System. The proposal is requesting support for a feature that is currently not supported.

- [x] I certify that this proposal does not replicate any existing design or functionality.

## Additional context

This request is for an Auro design spec to be addressed in conjunction with the re-develop of the prior existing component. 

This issue directly supports https://github.com/AlaskaAirlines/ods-inputoptions/issues/10, #24 and #26  

## Exit criteria

This issue will be considered complete once the UI has been applied to the WC and there is a static design asset that can be shared with all the product designers. 

There should be a reusable symbol added to the UIKit library as well as any static documentation to support that symbol. 

## Audit

https://github.com/AlaskaAirlines/auro_docs/issues/123

https://github.com/AlaskaAirlines/auro_docs/issues/122

**Comment by blackfalcon** [comment]
I am assuming that this is the direction that @gusnaughton is working on?

https://app.abstract.com/projects/2275e59a-5504-4c7d-b14d-52881b0a6db3/branches/master/files/528FCEE1-62FC-47B0-BFEF-D4511E580892/pages/40533CC5-A505-4257-88D1-4350494A39FB

**Comment by vidalmenAS** [comment]
@blackfalcon need to review shelby implementation one more time in the morning but will close this out tomorrow.

**Comment by blackfalcon** [comment]
Support: https://github.com/AlaskaAirlines/ods-inputoptions/issues/24
