### ISSUE TITLE
Events behave incorrectly with ods-inputoption (version 2.0)

### ISSUE THREAD

**Issue by geoffrich** [AlaskaAirlines/OrionStatelessComponents__ods-inputoptions#14]
## Describe the bug
The change event does not fire from ods-inputoptions (version 2.0) on checkbox change and the input event fires before the checked state has been updated.

## To Reproduce
1. Render ODS and vanilla checkboxes on the page
```html
<ods-inputoption-checkbox-group for="computers" label="Form label goes here">
  <ods-inputoption id="ods1" label="Computers" name="checkboxDemo1" type="checkbox" value="computers"></ods-inputoption>
  <ods-inputoption id="ods2" label="Arts" name="checkboxDemo1" type="checkbox" value="arts"></ods-inputoption>
  <ods-inputoption id="ods3" label="Sports" name="checkboxDemo1" type="checkbox" value="sports"></ods-inputoption>
  <ods-inputoption id="ods4" label="Machines" name="checkboxDemo1" type="checkbox" value="machines"></ods-inputoption>
</ods-inputoption-checkbox-group>

<div>
  <input type="checkbox" id="vanilla1" name="interest" value="coding">
  <label for="vanilla1">Coding</label>
</div>
<div>
  <input type="checkbox" id="vanilla2" name="interest" value="music">
  <label for="vanilla2">Music</label>
</div>
```
2. Attach event listeners
```js
const checkboxHandler = (e) => console.log(`${e.type}: ${e.target.id} ${e.target.checked}`     );

const odsCheckboxes = document.querySelectorAll('ods-inputoption');
odsCheckboxes.forEach(checkbox => checkbox.addEventListener('change', checkboxHandler));
odsCheckboxes.forEach(checkbox => checkbox.addEventListener('input', checkboxHandler));

const defaultCheckboxes = document.querySelectorAll('input[type="checkbox"]');
defaultCheckboxes.forEach(checkbox => checkbox.addEventListener('change', checkboxHandler));
defaultCheckboxes.forEach(checkbox => checkbox.addEventListener('input', checkboxHandler));
```
3. Check the ods-inputoption and see behavior in the console. Note that no change event was triggered and the checked state is undefined.
```
input: ods1 undefined
```
Uncheck the ods-inputoption and see behavior in the console. Note that no change event was triggered and the checked state is true, even though we unchecked the box.
```
input: ods1 true
```
4. Check the vanilla checkbox and see the expected behavior in the console
```
input: vanilla1 true
change: vanilla1 true
```
Uncheck the vanilla checkbox and see the expected behavior in the console
```
input: vanilla1 false 
change: vanilla1 false
```
## Expected behavior
When checking an ods-inputoption, an input and change event should fire after the component's state has been updated. If using my example, the console output should be the same as with a vanilla checkbox.

Until this is fixed, applications cannot use v2 of ods-inputoptions if they need to react to checkbox selections as they occur.

## Environment
 - OS: Windows 10
 - Browser: Chrome 81, Firefox 75

**Comment by blackfalcon** [comment]
If I remember correctly, this is what is needed. 

https://github.com/AlaskaAirlines/ods-inputoptions/blob/16278d676f5afda5958d2dd4b1156691cd803364/src/ods-inputoptions.js#L19

The issue is that the component needs to have the value of the input. But, was that what as causing this issue? https://github.com/AlaskaAirlines/ods-inputoptions/issues/9

**Comment by blackfalcon** [comment]
This also may be the issue 

https://github.com/AlaskaAirlines/ods-inputoptions/blob/master/src/ods-inputoption-base.js#L45

API
https://lit-element.polymer-project.org/guide/templates#bind-properties-to-templated-elements

**Comment by geoffrich** [comment]
> 
> 
> If I remember correctly, this is what is needed.
> 
> https://github.com/AlaskaAirlines/ods-inputoptions/blob/16278d676f5afda5958d2dd4b1156691cd803364/src/ods-inputoptions.js#L19
> 
> The issue is that the component needs to have the value of the input. But, was that what as causing this issue? #9

That could be why the checked value is undefined at first. However, I don't think it explains why the value of checked is the opposite of what it should be when the input event fires.

It also doesn't explain why [the element itself is able to respond to the change event](https://github.com/AlaskaAirlines/ods-inputoptions/blob/master/src/ods-inputoption-base.js#L39) fired by the input, but the change event doesn't continue propagating. Per [the LitElement docs](https://lit-element.polymer-project.org/guide/events#event-retargeting):

> Bubbling events fired from within shadow DOM are retargeted so that, to any listener external to your component, they appear to come from your component itself.

If I'm reading that correctly, then the change event should continue bubbling up, and appear to originate from ods-inputoption. For whatever reason that isn't happening. Do we need to fire our own change event after handling it from within the component?

**Comment by geoffrich** [comment]
Also something to remember -- IE11 does not fire input events for checkboxes. So even if we fix the input event, we still need the change event to be compatible with IE.

IE output for above example (note that no input event is triggered)
```
change: vanilla1 true
change: vanilla1 false
```

**Comment by blackfalcon** [comment]
We haven't dig into this yet, but the 1st place I want to look is at the missing `.value` property in the HTML template. 

My gut tells me that all we are missing is that unbound property.

**Comment by tsalright** [comment]
This is more than just checkboxes. Radio buttons on initial selection come through as undefined for each option in the group, then they always report out false on the input change.

**Comment by blackfalcon** [comment]
I would assume that this is the same for both as they are using much of the same code.
