### ISSUE TITLE
Unable to import "@alaskaairux/ods-inputoptions"

### ISSUE THREAD

**Issue by geoffrich** [AlaskaAirlines/OrionStatelessComponents__ods-inputoptions#15]
## Describe the bug
Importing the package [as listed in the README](https://github.com/AlaskaAirlines/ods-inputoptions/blob/master/README.md#define-dependency-in-project-component) throws an exception on build:

```js
import "@alaskaairux/ods-inputoptions";
```

```
[!] Error: Could not resolve './dist/ods-inputoptions' from node_modules\@alaskaairux\ods-inputoptions\index.js
Error: Could not resolve './dist/ods-inputoptions' from node_modules\@alaskaairux\ods-inputoptions\index.js
    at error (C:\Git\AuroSvelteDemo\node_modules\rollup\dist\shared\node-entry.js:5400:30)
    at ModuleLoader.handleResolveId (C:\Git\AuroSvelteDemo\node_modules\rollup\dist\shared\node-entry.js:12410:24)
    at ModuleLoader.<anonymous> (C:\Git\AuroSvelteDemo\node_modules\rollup\dist\shared\node-entry.js:12298:30)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Git\AuroSvelteDemo\node_modules\rollup\dist\shared\node-entry.js:38:28)
```

## To Reproduce
1. Import "@alaskaairux/ods-inputoptions"
2. Bundle your code
3. See the bundle error

## Expected behavior
No error. 

## Suggested fix
Update the `index.js` file to point to the new component files. 

## Additional context
Current workaround is to import the component files directly, e.g.

```js
import '@alaskaairux/ods-inputoptions/dist/ods-inputoption';
import '@alaskaairux/ods-inputoptions/dist/ods-inputoption-checkbox-group';
```

## Environment
- ods-inputoptions version: 2.0
- Bundler: Rollup 1.20
- OS: Windows 10

**Comment by blackfalcon** [comment]
there is a fix in the 2.0.1. version, but @gusnaughton is working on making that better.

**Comment by gusnaughton** [comment]
I think the best I can do for the barrel file is something where the Shadow DOM component is the default export and then just destructure the Light DOM component:

```
export default OdsInputoption from './dist/ods-inputoption'
export * from './dist/ods-inputoption-light'
import OdsInputOption, {OdsInputOptionLight} from '@alaskaairux/ods-inputoption'
```

but this feels inconsistent. I'd prefer destructuring both, but the above approach is consistent with how teams are used to importing packages. Alternative:

```
export * from './dist/ods-inputoption'
export * from './dist/ods-inputoption-light'
import {OdsInputOption, OdsInputOptionLight} from '@alaskaairux/ods-inputoption'
```

**Comment by blackfalcon** [comment]
I can get on board with 

```
export * from './dist/ods-inputoption'
export * from './dist/ods-inputoption-light'

import {OdsInputOption, OdsInputOptionLight} from '@alaskaairux/ods-inputoption'
```

**Comment by gusnaughton** [comment]
Because of the custom element .define() statement existing outside of the component class, destructuring does not work in this case. Importing by "@alaskaairux/ods-inputoptions" will define both ods-inputoptions and ods-inputoptions-light in the browser.
