### ISSUE TITLE
Unable to select input options in IE11

### ISSUE THREAD

**Issue by geoffrich** [AlaskaAirlines/OrionStatelessComponents__ods-inputoptions#16]
## Describe the bug
In IE11, clicking a checkbox or radio button does not select the checkbox or radio button. 

However, you can tab and hit the spacebar to select checkboxes. You can also tab to radio buttons, but using the up or down arrow keys to change your selection has no effect and produces the console error `Unable to get property 'renderRoot' of undefined or null reference`

This also happens on Edge 18, for what it's worth, with a `Out of stack space` console error instead. For some reason Edge hasn't updated to the Chromium build on my company-issued laptop.

Markup used:
```html
<h3>Default radio button group</h3>
<ods-inputoption-radio-group for="radio1" label="Form label goes here">
  <ods-inputoption id="radio1" label="Yes" name="radioDemo1" type="radio" value="yes"></ods-inputoption>
  <ods-inputoption id="radio2" label="No" name="radioDemo1" type="radio" value="no"></ods-inputoption>
  <ods-inputoption id="radio3" label="Maybe" name="radioDemo1" type="radio" value="maybe"></ods-inputoption>
</ods-inputoption-radio-group>

<h3>Default checkbox group</h3>
<ods-inputoption-checkbox-group for="computers" label="Form label goes here">
  <ods-inputoption id="computers" label="Computers" name="checkboxDemo1" type="checkbox" value="computers"></ods-inputoption>
  <ods-inputoption id="music" label="Music" name="checkboxDemo1" type="checkbox" value="music"></ods-inputoption>
  <ods-inputoption id="arts" label="Arts" name="checkboxDemo1" type="checkbox" value="arts"></ods-inputoption>
  <ods-inputoption id="sports" label="Sports" name="checkboxDemo1" type="checkbox" value="sports"></ods-inputoption>
  <ods-inputoption id="machines" label="Machines" name="checkboxDemo1" type="checkbox" value="machines"></ods-inputoption>
</ods-inputoption-checkbox-group>
```

## To Reproduce
1. Clone the odsinputoptions-v2 branch on my fork of the demo repo: https://github.com/geoffrey1218/OrionJavascriptDemo/tree/inputoptions-v2
2. Install dependencies with `npm install`
3. Start the dev server using `npm start`
4. Open `http://localhost:8080/` in IE and attempt to click on the checkbox and radio button. Notice that this does nothing.
5. Tab to the radio button and hit the down arrow. Notice that this does nothing and triggers a console error.

## Expected behavior
You can click to select input options in IE11. You can also tab to radio buttons and change your selection with the arrow keys.

## Environment
OS: Windows 10
Browser: IE11/Edge 18
Package version: 2.0.1

**Comment by blackfalcon** [comment]
This one is crazy to me? I tested this in IE? 

As for Edge, going from 18 to Chrome is a manual process. There is no auto-update for that.

**Comment by blackfalcon** [comment]
See https://github.com/AlaskaAirlines/ods-inputoptions/issues/10 for information about de-scoping. 

Closing this issue as ods-inputOptions is now deprecated.
