### ISSUE TITLE
Multiple radio buttons selectable (Firefox only)

### ISSUE THREAD

**Issue by geoffrich** [AlaskaAirlines/OrionStatelessComponents__ods-inputoptions#17]
## Describe the bug
In Firefox it is possible to select multiple radio buttons in the same `ods-inputoption-radio-group`. This does not appear to happen in Chrome.

Markup used:
```html
<ods-inputoption-radio-group for="radio1" label="Form label goes here">
  <ods-inputoption id="radio1" label="Yes" name="radioDemo1" type="radio" value="yes"></ods-inputoption>
  <ods-inputoption id="radio2" label="No" name="radioDemo1" type="radio" value="no"></ods-inputoption>
  <ods-inputoption id="radio3" label="Maybe" name="radioDemo1" type="radio" value="maybe"></ods-inputoption>
</ods-inputoption-radio-group>
```

## To Reproduce
1. Render the above markup. Open in Firefox.
2. Hit tab once to focus the first radio button. Hit space to select it.
3. Hit tab again to focus the second radio button. Hit space to select it.
4. Hit tab once more to focus the third radio button. Hit space to select it.

Note: for some reason, hitting an arrow key will stop the tab key from focusing the next radio button and focus will behave as expected.

## Expected behavior
Multiple radio buttons in the same group are not selectable at the same time. In addition, hitting tab within a radio group focuses the next element after the radio button, not the next radio button.

## Screenshots
![image](https://user-images.githubusercontent.com/4992896/81238538-32a9d700-8fb7-11ea-8a67-58a6c394412e.png)

## Environment
- OS: Windows 10
- Browser: Firefox 76
- Package version: 2.0.1

## Audit

https://github.com/AlaskaAirlines/auro_docs/issues/123

**Comment by blackfalcon** [comment]
This issue also somewhat appears in Safari. The main issue being the movement of the tabbed state. This appears to be an issue with focus-visible. So the solution to that could simply be CSS to follow the tab state.

**Comment by blackfalcon** [comment]
See https://github.com/AlaskaAirlines/ods-inputoptions/issues/10 for information about de-scoping. 

Closing this issue as ods-inputOptions is now deprecated.
