### ISSUE TITLE
Tab key needs to be hit twice to move focus in some cases

### ISSUE THREAD

**Issue by geoffrich** [AlaskaAirlines/OrionStatelessComponents__ods-inputoptions#19]
## Describe the bug
In some cases, you have to hit the tab key twice to move focus between groups of radio buttons.

Markup used:
```html
<ods-inputoption-radio-group for="radio1" label="Form label goes here">
  <ods-inputoption id="radio1" label="Yes" name="radioDemo1" type="radio" value="yes"></ods-inputoption>
  <ods-inputoption id="radio2" label="No" name="radioDemo1" type="radio" value="no"></ods-inputoption>
  <ods-inputoption id="radio3" label="Maybe" name="radioDemo1" type="radio" value="maybe"></ods-inputoption>
</ods-inputoption-radio-group>

<ods-inputoption-radio-group for="radio4" label="Form label goes here">
  <ods-inputoption id="radio4" label="Yes" name="radioDemo2" type="radio" value="yes"></ods-inputoption>
  <ods-inputoption id="radio5" label="No" name="radioDemo2" type="radio" value="no"></ods-inputoption>
  <ods-inputoption id="radio6" label="Maybe" name="radioDemo2" type="radio" value="maybe"></ods-inputoption>
</ods-inputoption-radio-group>
```

## To Reproduce
1. Render the markup into your browser
2. Tab to the first radio group. Hit tab again to tab to the second radio group.
3. Hit the down arrow to select the second item in the second radio group
4. Hit shift+Tab to move back to the previous radio group. Nothing happens, and you have to hit shift+Tab again to move focus.

## Expected behavior
Shift+Tab only needs to be hit once to move focus in the case described above.

## Environment
OS: Windows 10
Browser: Chrome 81
Package version: 2.0.1

**Comment by blackfalcon** [comment]
See https://github.com/AlaskaAirlines/ods-inputoptions/issues/10 for information about de-scoping. 

Closing this issue as ods-inputOptions is now deprecated.
