### ISSUE TITLE
Value property for radio button is inconsistent with docs

### ISSUE THREAD

**Issue by geoffrich** [AlaskaAirlines/OrionStatelessComponents__ods-inputoptions#7]
# Issue report

## Expected Behavior

The `value` property returns an array when type is radio.

## Current Behavior

The `value` property returns a string when type is radio.

## Steps to Reproduce (for bugs)

1. Run the demo page for the component
2. Access the value of the first inputoptions in the console. It returns `[]`
3. Select the first radio button. 
4. Access the value again. It now returns `"yes"`

## Proposed Solution
The API should be consistent. Either the docs should be updated to say that the value of a radio is a string and the initial value should be empty string, or the code should be updated to return an array for type radio. The latter option may be a breaking change.

## Your Environment

* Version used: 1.1.5
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Windows 7

**Comment by AuroDesignSystem** [comment]
Issue no longer an issue due to re-write of inputs component(s).
