### ISSUE TITLE
onInput event firing twice

### ISSUE THREAD

**Issue by aaronluannguyen** [AlaskaAirlines/OrionStatelessComponents__ods-inputoptions#9]
# Issue report
## Expected Behavior
- onInput event should fire once
- onChange does not fire an event

## Current Behavior
- onInput event fires twice
- onChange should fire an event

## Possible Solution
- Talked with Geoff, and he mentioned that he could have something to do with how ods-inputoptions is surfacing the events 

## Steps to Reproduce (for bugs)
https://github.com/AlaskaAirlines/OrionReactDemo/blob/master/src/Components.js#L62
- Link above was to the demo site github. Should be able to clone and run the site locally with a custom console log onInput, and you should see two events fired twice.

## Context
- Trying to omniture tag how our users are changing their mind when preordering

## Your Environment
* Browser Name and version: Chrome Version 78.0.3904.108 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Desktop Windows

**Comment by blackfalcon** [comment]
@aaronluannguyen is this causing a functional issue with your current application? 

If not, I am inclined to not address this as we are working on a full replacement for this component. If you are able, a pull request with a suggested change would be very helpful.
